import { Octokit } from 'octokit';
import { getSetting } from './database.js';

export async function createGitHubRepo(repoName, description, allFiles) {
  const token = process.env.GITHUB_TOKEN || getSetting('github_token');
  if (!token) throw new Error('GitHub token not configured');

  const octokit = new Octokit({ auth: token });

  const sanitizedName = repoName
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .substring(0, 100);

  let repo;
  try {
    const { data } = await octokit.rest.repos.createForAuthenticatedUser({
      name: sanitizedName,
      description: description || 'Generated by AutoShip AI',
      private: false,
      auto_init: true,
    });
    repo = data;
  } catch (err) {
    if (err.status === 422) {
      const { data: user } = await octokit.rest.users.getAuthenticated();
      const { data } = await octokit.rest.repos.get({
        owner: user.login,
        repo: sanitizedName,
      });
      repo = data;
    } else {
      throw err;
    }
  }

  const owner = repo.owner.login;

  // Wait briefly for repo initialization
  await new Promise(resolve => setTimeout(resolve, 2000));

  let baseTreeSha;
  let branchRef = 'heads/main';
  try {
    const { data: ref } = await octokit.rest.git.getRef({
      owner,
      repo: sanitizedName,
      ref: 'heads/main',
    });
    baseTreeSha = ref.object.sha;
  } catch {
    try {
      const { data: ref } = await octokit.rest.git.getRef({
        owner,
        repo: sanitizedName,
        ref: 'heads/master',
      });
      baseTreeSha = ref.object.sha;
      branchRef = 'heads/master';
    } catch {
      baseTreeSha = null;
    }
  }

  const treeItems = [];
  for (const [filePath, content] of Object.entries(allFiles)) {
    const { data: blob } = await octokit.rest.git.createBlob({
      owner,
      repo: sanitizedName,
      content: Buffer.from(content).toString('base64'),
      encoding: 'base64',
    });

    treeItems.push({
      path: filePath,
      mode: '100644',
      type: 'blob',
      sha: blob.sha,
    });
  }

  const treeParams = {
    owner,
    repo: sanitizedName,
    tree: treeItems,
  };
  if (baseTreeSha) {
    const { data: commit } = await octokit.rest.git.getCommit({
      owner,
      repo: sanitizedName,
      commit_sha: baseTreeSha,
    });
    treeParams.base_tree = commit.tree.sha;
  }

  const { data: tree } = await octokit.rest.git.createTree(treeParams);

  const commitParams = {
    owner,
    repo: sanitizedName,
    message: 'feat: auto-generated application by AutoShip AI',
    tree: tree.sha,
  };
  if (baseTreeSha) {
    commitParams.parents = [baseTreeSha];
  }

  const { data: commit } = await octokit.rest.git.createCommit(commitParams);

  await octokit.rest.git.updateRef({
    owner,
    repo: sanitizedName,
    ref: branchRef,
    sha: commit.sha,
  });

  return repo.html_url;
}